version: "3"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    volumes:
      - ./api:/usr/src/app
